# Sample Prices

In [5]:
from mplchart.samples import sample_prices, SAMPLE_FREQUENCIES

In [6]:
for freq in SAMPLE_FREQUENCIES:
    prices = sample_prices(freq)
    index = prices.index
    print(freq, len(prices), index.dtype)

daily 11325 datetime64[ns]
hourly 3480 datetime64[ns, America/New_York]
minute 2730 datetime64[ns, America/New_York]

In [7]:
for freq in SAMPLE_FREQUENCIES:
    prices = sample_prices(freq, backend="polars")
    print(freq, len(prices), prices['datetime'].dtype)

daily 11325 Datetime(time_unit='ns', time_zone=None)
hourly 3480 Datetime(time_unit='ns', time_zone='America/New_York')
minute 2730 Datetime(time_unit='ns', time_zone='America/New_York')

In [8]:
prices = sample_prices(freq="daily")
prices

                  open        high         low       close     volume
datetime
1980-12-12    0.098389    0.098817    0.098389    0.098389  469033600
1980-12-15    0.093684    0.093684    0.093256    0.093256  175884800
1980-12-16    0.086839    0.086839    0.086412    0.086412  105728000
1980-12-17    0.088550    0.088978    0.088550    0.088550   86441600
1980-12-18    0.091118    0.091545    0.091118    0.091118   73449600
...                ...         ...         ...         ...        ...
2025-11-11  269.809998  275.910004  269.799988  275.250000   46208300
2025-11-12  275.000000  275.730011  271.700012  273.470001   48398000
2025-11-13  274.109985  276.700012  272.089996  272.950012   49602800
2025-11-14  271.049988  275.959991  269.600006  272.410004   47399300
2025-11-17  268.815002  270.489990  265.730011  267.459991   42862157

[11325 rows x 5 columns]

In [10]:
prices.rename(columns=dict(volume="vol"))

                  open        high         low       close        vol
datetime
1980-12-12    0.098389    0.098817    0.098389    0.098389  469033600
1980-12-15    0.093684    0.093684    0.093256    0.093256  175884800
1980-12-16    0.086839    0.086839    0.086412    0.086412  105728000
1980-12-17    0.088550    0.088978    0.088550    0.088550   86441600
1980-12-18    0.091118    0.091545    0.091118    0.091118   73449600
...                ...         ...         ...         ...        ...
2025-11-11  269.809998  275.910004  269.799988  275.250000   46208300
2025-11-12  275.000000  275.730011  271.700012  273.470001   48398000
2025-11-13  274.109985  276.700012  272.089996  272.950012   49602800
2025-11-14  271.049988  275.959991  269.600006  272.410004   47399300
2025-11-17  268.815002  270.489990  265.730011  267.459991   42862157

[11325 rows x 5 columns]