# Date Mapper Tests

In [1]:
import pandas as pd

from mplchart.samples import sample_prices
from mplchart.dataview import PandasDataView

In [2]:
ticker = "AAPL"
prices = sample_prices(max_bars=5000)
prices

                  open        high         low       close      volume
date
2006-01-04    2.253227    2.278719    2.234332    2.248429   619603600
2006-01-05    2.244230    2.246329    2.211840    2.230735   449422400
2006-01-06    2.256826    2.300314    2.235833    2.288317   704457600
2006-01-09    2.301212    2.315309    2.271521    2.280818   675040800
2006-01-10    2.286817    2.455967    2.274221    2.425076  2279869200
...                ...         ...         ...         ...         ...
2025-11-11  269.809998  275.910004  269.799988  275.250000    46208300
2025-11-12  275.000000  275.730011  271.700012  273.470001    48398000
2025-11-13  274.109985  276.700012  272.089996  272.950012    49602800
2025-11-14  271.049988  275.959991  269.600006  272.410004    47399300
2025-11-17  268.815002  270.489990  265.730011  267.459991    42862157

[5000 rows x 5 columns]

In [3]:
view = PandasDataView(prices, max_bars=10)
view

In [4]:
view.slice(prices)

            open        high         low       close    volume
xloc
4990  268.070107  271.227050  267.360803  269.778473  49274800
4991  268.349840  271.436874  266.671474  269.878387  43683100
4992  267.630574  273.135217  267.630574  269.508728  51204000
4993  269.538690  272.026299  266.511626  268.209991  48227400
4994  268.959991  273.730011  267.459991  269.429993  41312400
4995  269.809998  275.910004  269.799988  275.250000  46208300
4996  275.000000  275.730011  271.700012  273.470001  48398000
4997  274.109985  276.700012  272.089996  272.950012  49602800
4998  271.049988  275.959991  269.600006  272.410004  47399300
4999  268.815002  270.489990  265.730011  267.459991  42862157

In [5]:
prices2 = pd.concat([prices, prices]).sort_index()
prices2

                  open        high         low       close     volume
date
2006-01-04    2.253227    2.278719    2.234332    2.248429  619603600
2006-01-04    2.253227    2.278719    2.234332    2.248429  619603600
2006-01-05    2.244230    2.246329    2.211840    2.230735  449422400
2006-01-05    2.244230    2.246329    2.211840    2.230735  449422400
2006-01-06    2.256826    2.300314    2.235833    2.288317  704457600
...                ...         ...         ...         ...        ...
2025-11-13  274.109985  276.700012  272.089996  272.950012   49602800
2025-11-14  271.049988  275.959991  269.600006  272.410004   47399300
2025-11-14  271.049988  275.959991  269.600006  272.410004   47399300
2025-11-17  268.815002  270.489990  265.730011  267.459991   42862157
2025-11-17  268.815002  270.489990  265.730011  267.459991   42862157

[10000 rows x 5 columns]

In [6]:
view.slice(prices2)

            open        high         low       close    volume
xloc
4990  268.070107  271.227050  267.360803  269.778473  49274800
4990  268.070107  271.227050  267.360803  269.778473  49274800
4991  268.349840  271.436874  266.671474  269.878387  43683100
4991  268.349840  271.436874  266.671474  269.878387  43683100
4992  267.630574  273.135217  267.630574  269.508728  51204000
4992  267.630574  273.135217  267.630574  269.508728  51204000
4993  269.538690  272.026299  266.511626  268.209991  48227400
4993  269.538690  272.026299  266.511626  268.209991  48227400
4994  268.959991  273.730011  267.459991  269.429993  41312400
4994  268.959991  273.730011  267.459991  269.429993  41312400
4995  269.809998  275.910004  269.799988  275.250000  46208300
4995  269.809998  275.910004  269.799988  275.250000  46208300
4996  275.000000  275.730011  271.700012  273.470001  48398000
4996  275.000000  275.730011  271.700012  273.470001  48398000
4997  274.109985  276.700012  272.089996  272.950012  49602800
4997  274.109985  276.700012  272.089996  272.950012  49602800
4998  271.049988  275.959991  269.600006  272.410004  47399300
4998  271.049988  275.959991  269.600006  272.410004  47399300
4999  268.815002  270.489990  265.730011  267.459991  42862157
4999  268.815002  270.489990  265.730011  267.459991  42862157