# Pandas DateTimeIndex (playground)

In [1]:
import numpy as np
import pandas as pd

from datetime import date

from mplchart.samples import sample_prices

In [2]:
freq = "daily"
prices = sample_prices(freq, max_bars=5000)
prices

                  open        high         low       close      volume
date
2006-01-04    2.253227    2.278719    2.234332    2.248429   619603600
2006-01-05    2.244230    2.246329    2.211840    2.230735   449422400
2006-01-06    2.256826    2.300314    2.235833    2.288317   704457600
2006-01-09    2.301212    2.315309    2.271521    2.280818   675040800
2006-01-10    2.286817    2.455967    2.274221    2.425076  2279869200
...                ...         ...         ...         ...         ...
2025-11-11  269.809998  275.910004  269.799988  275.250000    46208300
2025-11-12  275.000000  275.730011  271.700012  273.470001    48398000
2025-11-13  274.109985  276.700012  272.089996  272.950012    49602800
2025-11-14  271.049988  275.959991  269.600006  272.410004    47399300
2025-11-17  268.815002  270.489990  265.730011  267.459991    42862157

[5000 rows x 5 columns]

In [3]:
index = prices.index
index

DatetimeIndex(['2006-01-04', '2006-01-05', '2006-01-06', '2006-01-09',
               '2006-01-10', '2006-01-11', '2006-01-12', '2006-01-13',
               '2006-01-17', '2006-01-18',
               ...
               '2025-11-04', '2025-11-05', '2025-11-06', '2025-11-07',
               '2025-11-10', '2025-11-11', '2025-11-12', '2025-11-13',
               '2025-11-14', '2025-11-17'],
              dtype='datetime64[us]', name='date', length=5000, freq=None)

In [4]:
type(index)

pandas.DatetimeIndex

In [5]:
index.tz_localize(None)

DatetimeIndex(['2006-01-04', '2006-01-05', '2006-01-06', '2006-01-09',
               '2006-01-10', '2006-01-11', '2006-01-12', '2006-01-13',
               '2006-01-17', '2006-01-18',
               ...
               '2025-11-04', '2025-11-05', '2025-11-06', '2025-11-07',
               '2025-11-10', '2025-11-11', '2025-11-12', '2025-11-13',
               '2025-11-14', '2025-11-17'],
              dtype='datetime64[us]', name='date', length=5000, freq=None)

In [6]:

index.date

array([datetime.date(2006, 1, 4), datetime.date(2006, 1, 5),
       datetime.date(2006, 1, 6), ..., datetime.date(2025, 11, 13),
       datetime.date(2025, 11, 14), datetime.date(2025, 11, 17)],
      shape=(5000,), dtype=object)

In [7]:
index.tz

In [8]:
start, end = date(1960, 1, 1), date(2025, 12, 31)
start, end = None, None
locs = index.tz_localize(None).slice_indexer(start=start, end=end)
print(locs)
index[locs]

slice(0, 5000, None)

DatetimeIndex(['2006-01-04', '2006-01-05', '2006-01-06', '2006-01-09',
               '2006-01-10', '2006-01-11', '2006-01-12', '2006-01-13',
               '2006-01-17', '2006-01-18',
               ...
               '2025-11-04', '2025-11-05', '2025-11-06', '2025-11-07',
               '2025-11-10', '2025-11-11', '2025-11-12', '2025-11-13',
               '2025-11-14', '2025-11-17'],
              dtype='datetime64[us]', name='date', length=5000, freq=None)

In [9]:
max_bars = 5

print(locs)

start = locs.start
stop = locs.stop or len(index)

if stop - start > max_bars:
    start = stop - max_bars
    locs = slice(start, stop)

print(locs)

slice(0, 5000, None)
slice(4995, 5000, None)

In [10]:
xloc = pd.Series(np.arange(len(index)), index=index, name="xloc")

xloc, data = xloc.align(prices, join="inner")

data = data.reset_index().set_axis(xloc)

data

           date        open        high         low       close      volume
xloc
0    2006-01-04    2.253227    2.278719    2.234332    2.248429   619603600
1    2006-01-05    2.244230    2.246329    2.211840    2.230735   449422400
2    2006-01-06    2.256826    2.300314    2.235833    2.288317   704457600
3    2006-01-09    2.301212    2.315309    2.271521    2.280818   675040800
4    2006-01-10    2.286817    2.455967    2.274221    2.425076  2279869200
...         ...         ...         ...         ...         ...         ...
4995 2025-11-11  269.809998  275.910004  269.799988  275.250000    46208300
4996 2025-11-12  275.000000  275.730011  271.700012  273.470001    48398000
4997 2025-11-13  274.109985  276.700012  272.089996  272.950012    49602800
4998 2025-11-14  271.049988  275.959991  269.600006  272.410004    47399300
4999 2025-11-17  268.815002  270.489990  265.730011  267.459991    42862157

[5000 rows x 6 columns]

In [11]:
tuple(data.index.names) == ("xloc",)

True

In [12]:


data.loc[slice(0, 5000, 2)].loc[locs]

           date        open        high         low       close    volume
xloc
4996 2025-11-12  275.000000  275.730011  271.700012  273.470001  48398000
4998 2025-11-14  271.049988  275.959991  269.600006  272.410004  47399300

In [13]:
data.loc[slice(4995, 4999, None)]

           date        open        high         low       close    volume
xloc
4995 2025-11-11  269.809998  275.910004  269.799988  275.250000  46208300
4996 2025-11-12  275.000000  275.730011  271.700012  273.470001  48398000
4997 2025-11-13  274.109985  276.700012  272.089996  272.950012  49602800
4998 2025-11-14  271.049988  275.959991  269.600006  272.410004  47399300
4999 2025-11-17  268.815002  270.489990  265.730011  267.459991  42862157

In [14]:
index[slice(4995, 4999, None)]

DatetimeIndex(['2025-11-11', '2025-11-12', '2025-11-13', '2025-11-14'], dtype='datetime64[us]', name='date', freq=None)