# Pandas DateTimeIndex (playground)

In [1]:
import numpy as np
import pandas as pd

from datetime import date

from mplchart.samples import sample_prices

In [2]:
freq = "daily"
prices = sample_prices(freq, max_bars=5000)
prices

                  open        high         low       close      volume
date
2006-09-20    2.226597    2.265512    2.221806    2.252939   822791200
2006-09-21    2.252641    2.276889    2.215820    2.234679   794124800
2006-09-22    2.224202    2.225399    2.172713    2.185286   665112000
2006-09-25    2.209534    2.270902    2.206840    2.267609   858992400
2006-09-26    2.280480    2.328377    2.278085    2.323288  1102948000
...                ...         ...         ...         ...         ...
2026-07-31  304.809998  310.690002  300.000000  308.910004   132489100
2026-08-03  309.579987  311.799988  302.559998  303.420013    75052000
2026-08-04  302.730011  310.420013  301.320007  309.380005    68001000
2026-08-05  309.359985  311.709991  305.670013  311.000000    49178700
2026-08-06  314.339996  316.289398  313.450012  313.500000     7837945

[5000 rows x 5 columns]

In [3]:
from typing import cast

index = cast(pd.DatetimeIndex, prices.index)

index

DatetimeIndex(['2006-09-20', '2006-09-21', '2006-09-22', '2006-09-25',
               '2006-09-26', '2006-09-27', '2006-09-28', '2006-09-29',
               '2006-10-02', '2006-10-03',
               ...
               '2026-07-24', '2026-07-27', '2026-07-28', '2026-07-29',
               '2026-07-30', '2026-07-31', '2026-08-03', '2026-08-04',
               '2026-08-05', '2026-08-06'],
              dtype='datetime64[us]', name='date', length=5000, freq=None)

In [4]:
type(index)

pandas.DatetimeIndex

In [5]:
index.tz_localize(None)

DatetimeIndex(['2006-09-20', '2006-09-21', '2006-09-22', '2006-09-25',
               '2006-09-26', '2006-09-27', '2006-09-28', '2006-09-29',
               '2006-10-02', '2006-10-03',
               ...
               '2026-07-24', '2026-07-27', '2026-07-28', '2026-07-29',
               '2026-07-30', '2026-07-31', '2026-08-03', '2026-08-04',
               '2026-08-05', '2026-08-06'],
              dtype='datetime64[us]', name='date', length=5000, freq=None)

In [ ]:

index.date # ty: ignore[unresolved-attribute]

array([datetime.date(2006, 9, 20), datetime.date(2006, 9, 21),
       datetime.date(2006, 9, 22), ..., datetime.date(2026, 8, 4),
       datetime.date(2026, 8, 5), datetime.date(2026, 8, 6)],
      shape=(5000,), dtype=object)

In [7]:
index.tz

In [8]:
start, end = date(1960, 1, 1), date(2025, 12, 31)
start, end = None, None
locs = index.tz_localize(None).slice_indexer(start=start, end=end)
print(locs)
index[locs]

slice(0, 5000, None)

DatetimeIndex(['2006-09-20', '2006-09-21', '2006-09-22', '2006-09-25',
               '2006-09-26', '2006-09-27', '2006-09-28', '2006-09-29',
               '2006-10-02', '2006-10-03',
               ...
               '2026-07-24', '2026-07-27', '2026-07-28', '2026-07-29',
               '2026-07-30', '2026-07-31', '2026-08-03', '2026-08-04',
               '2026-08-05', '2026-08-06'],
              dtype='datetime64[us]', name='date', length=5000, freq=None)

In [9]:
max_bars = 5

print(locs)

start = locs.start
stop = locs.stop or len(index)

if stop - start > max_bars:
    start = stop - max_bars
    locs = slice(start, stop)

print(locs)

slice(0, 5000, None)
slice(4995, 5000, None)

In [10]:
xloc = pd.Series(np.arange(len(index)), index=index, name="xloc")

xloc, data = xloc.align(prices, join="inner")

data = data.reset_index().set_axis(xloc)

data

           date        open        high         low       close      volume
xloc
0    2006-09-20    2.226597    2.265512    2.221806    2.252939   822791200
1    2006-09-21    2.252641    2.276889    2.215820    2.234679   794124800
2    2006-09-22    2.224202    2.225399    2.172713    2.185286   665112000
3    2006-09-25    2.209534    2.270902    2.206840    2.267609   858992400
4    2006-09-26    2.280480    2.328377    2.278085    2.323288  1102948000
...         ...         ...         ...         ...         ...         ...
4995 2026-07-31  304.809998  310.690002  300.000000  308.910004   132489100
4996 2026-08-03  309.579987  311.799988  302.559998  303.420013    75052000
4997 2026-08-04  302.730011  310.420013  301.320007  309.380005    68001000
4998 2026-08-05  309.359985  311.709991  305.670013  311.000000    49178700
4999 2026-08-06  314.339996  316.289398  313.450012  313.500000     7837945

[5000 rows x 6 columns]

In [11]:
tuple(data.index.names) == ("xloc",)

True

In [12]:


data.loc[slice(0, 5000, 2)].loc[locs]

           date        open        high         low       close    volume
xloc
4996 2026-08-03  309.579987  311.799988  302.559998  303.420013  75052000
4998 2026-08-05  309.359985  311.709991  305.670013  311.000000  49178700

In [13]:
data.loc[slice(4995, 4999, None)]

           date        open        high         low       close     volume
xloc
4995 2026-07-31  304.809998  310.690002  300.000000  308.910004  132489100
4996 2026-08-03  309.579987  311.799988  302.559998  303.420013   75052000
4997 2026-08-04  302.730011  310.420013  301.320007  309.380005   68001000
4998 2026-08-05  309.359985  311.709991  305.670013  311.000000   49178700
4999 2026-08-06  314.339996  316.289398  313.450012  313.500000    7837945

In [14]:
index[slice(4995, 4999, None)]

DatetimeIndex(['2026-07-31', '2026-08-03', '2026-08-04', '2026-08-05'], dtype='datetime64[us]', name='date', freq=None)