# Rebase Series Example (pandas)

In [ ]:
import yfinance as yf

from mplchart.chart import Chart
from mplchart.primitives import Candlesticks, Volume, LinePlot
from mplchart.indicators import SMA, RSI, MACD
from mplchart.utils import normalize_prices

In [2]:
ticker = "AAPL"
aapl = normalize_prices(yf.Ticker(ticker).history(period="5y"))
aapl

,open,high,low,close,volume,dividends,stock splits
date,,,,,,,
2021-03-01 00:00:00-05:00,120.531946,124.603247,119.596911,124.466888,116307900,0.0,0.0
2021-03-02 00:00:00-05:00,125.070795,125.372731,121.759208,121.866348,102260900,0.0,0.0
2021-03-03 00:00:00-05:00,121.564390,122.440988,118.671622,118.885902,112966300,0.0,0.0
2021-03-04 00:00:00-05:00,118.583979,120.385870,115.535375,117.006104,178155000,0.0,0.0
2021-03-05 00:00:00-05:00,117.833990,118.769025,114.512661,118.262543,153766600,0.0,0.0
...,...,...,...,...,...,...,...
2026-02-23 00:00:00-05:00,263.489990,269.429993,263.380005,266.179993,37308200,0.0,0.0
2026-02-24 00:00:00-05:00,267.859985,274.890015,267.709991,272.140015,47014600,0.0,0.0
2026-02-25 00:00:00-05:00,271.779999,274.940002,271.049988,274.230011,33714300,0.0,0.0
2026-02-26 00:00:00-05:00,274.950012,276.109985,270.799988,272.950012,32345100,0.0,0.0
2026-02-27 00:00:00-05:00,272.809998,272.809998,262.890015,264.179993,72239400,0.0,0.0

In [3]:
ticker = "MSFT"
msft = normalize_prices(yf.Ticker(ticker).history(period="5y"))
msft

,open,high,low,close,volume,dividends,stock splits
date,,,,,,,
2021-03-01 00:00:00-05:00,226.360097,227.866613,223.721309,227.358047,25324000,0.0,0.0
2021-03-02 00:00:00-05:00,227.425248,227.703529,224.009218,224.412231,22812500,0.0,0.0
2021-03-03 00:00:00-05:00,222.771387,224.133960,218.069536,218.357407,34029500,0.0,0.0
2021-03-04 00:00:00-05:00,217.570564,223.088032,215.190845,217.560959,44727800,0.0,0.0
2021-03-05 00:00:00-05:00,220.238123,223.836472,217.301873,222.234009,41872800,0.0,0.0
...,...,...,...,...,...,...,...
2026-02-23 00:00:00-05:00,395.000000,395.359985,383.100006,384.470001,43238300,0.0,0.0
2026-02-24 00:00:00-05:00,384.140015,389.359985,381.709991,389.000000,33884700,0.0,0.0
2026-02-25 00:00:00-05:00,390.529999,401.470001,390.160004,400.600006,43625500,0.0,0.0
2026-02-26 00:00:00-05:00,404.709991,407.489990,398.739990,401.720001,34405900,0.0,0.0
2026-02-27 00:00:00-05:00,390.880005,396.820007,389.880005,392.739990,51276300,0.0,0.0

In [4]:
from mplchart.pandas import merge_prices

prices = merge_prices(aapl, msft=msft.close, rebase=True)
prices

,open,high,low,close,volume,dividends,stock splits,msft
date,,,,,,,,
2021-03-01 00:00:00-05:00,120.531946,124.603247,119.596911,124.466888,116307900,0.0,0.0,124.466888
2021-03-02 00:00:00-05:00,125.070795,125.372731,121.759208,121.866348,102260900,0.0,0.0,122.854205
2021-03-03 00:00:00-05:00,121.564390,122.440988,118.671622,118.885902,112966300,0.0,0.0,119.539498
2021-03-04 00:00:00-05:00,118.583979,120.385870,115.535375,117.006104,178155000,0.0,0.0,119.103484
2021-03-05 00:00:00-05:00,117.833990,118.769025,114.512661,118.262543,153766600,0.0,0.0,121.661740
...,...,...,...,...,...,...,...,...
2026-02-23 00:00:00-05:00,263.489990,269.429993,263.380005,266.179993,37308200,0.0,0.0,210.477638
2026-02-24 00:00:00-05:00,267.859985,274.890015,267.709991,272.140015,47014600,0.0,0.0,212.957580
2026-02-25 00:00:00-05:00,271.779999,274.940002,271.049988,274.230011,33714300,0.0,0.0,219.307989
2026-02-26 00:00:00-05:00,274.950012,276.109985,270.799988,272.950012,32345100,0.0,0.0,219.921129
2026-02-27 00:00:00-05:00,272.809998,272.809998,262.890015,264.179993,72239400,0.0,0.0,215.005033

In [ ]:
# Plot with merged series 

title = "AAPL vs MSFT"
max_bars = 250

indicators = [
    Candlesticks(),
    LinePlot("msft"),
    Volume(),
]

Chart(prices, title=title, max_bars=max_bars).plot(indicators).show()