# Talib Functions (playground)

In [35]:
import pandas as pd
import yfinance as yf

from talib import get_functions
from talib import abstract
from talib.abstract import Function

from mplchart.chart import Chart
from mplchart.samples import sample_prices
from mplchart.primitives import Candlesticks

from IPython.display import display

In [36]:
prices = sample_prices()
prices

                  open        high         low       close     volume
date
1980-12-12    0.099058    0.099488    0.099058    0.099058  469033600
1980-12-15    0.094321    0.094321    0.093890    0.093890  175884800
1980-12-16    0.087429    0.087429    0.086999    0.086999  105728000
1980-12-17    0.089152    0.089582    0.089152    0.089152   86441600
1980-12-18    0.091736    0.092167    0.091736    0.091736   73449600
...                ...         ...         ...         ...        ...
2024-05-29  189.610001  192.250000  189.509995  190.289993   53068000
2024-05-30  190.759995  192.179993  190.630005  191.289993   49947900
2024-05-31  191.440002  192.570007  189.910004  192.250000   75158300
2024-06-03  192.899994  194.990005  192.520004  194.029999   50031100
2024-06-04  194.720001  195.320007  193.034195  194.529999   29703490

[10960 rows x 5 columns]

In [37]:
functions = [Function(name).info for name in get_functions()]
functions = pd.DataFrame(functions).set_index("name")
functions

,group,display_name,function_flags,input_names,parameters,output_flags,output_names
name,,,,,,,
HT_DCPERIOD,Cycle Indicators,Hilbert Transform - Dominant Cycle Period,[Function has an unstable period],{'price': 'close'},{},{'real': ['Line']},[real]
HT_DCPHASE,Cycle Indicators,Hilbert Transform - Dominant Cycle Phase,[Function has an unstable period],{'price': 'close'},{},{'real': ['Line']},[real]
HT_PHASOR,Cycle Indicators,Hilbert Transform - Phasor Components,[Function has an unstable period],{'price': 'close'},{},"{'inphase': ['Line'], 'quadrature': ['Dashed L...","[inphase, quadrature]"
HT_SINE,Cycle Indicators,Hilbert Transform - SineWave,[Function has an unstable period],{'price': 'close'},{},"{'sine': ['Line'], 'leadsine': ['Dashed Line']}","[sine, leadsine]"
HT_TRENDMODE,Cycle Indicators,Hilbert Transform - Trend vs Cycle Mode,[Function has an unstable period],{'price': 'close'},{},{'integer': ['Line']},[integer]
...,...,...,...,...,...,...,...
NATR,Volatility Indicators,Normalized Average True Range,[Function has an unstable period],"{'prices': ['high', 'low', 'close']}",{'timeperiod': 14},{'real': ['Line']},[real]
TRANGE,Volatility Indicators,True Range,None,"{'prices': ['high', 'low', 'close']}",{},{'real': ['Line']},[real]
AD,Volume Indicators,Chaikin A/D Line,None,"{'prices': ['high', 'low', 'close', 'volume']}",{},{'real': ['Line']},[real]
ADOSC,Volume Indicators,Chaikin A/D Oscillator,None,"{'prices': ['high', 'low', 'close', 'volume']}","{'fastperiod': 3, 'slowperiod': 10}",{'real': ['Line']},[real]
OBV,Volume Indicators,On Balance Volume,None,"{'price': 'close', 'prices': ['volume']}",{},{'real': ['Line']},[real]

In [ ]:
flags = [
    (name, item, ":".join(flags))
    for name in get_functions()
    for item, flags in Function(name).output_flags.items()
]

flags = pd.DataFrame.from_records(flags, columns=["name", "item", "flag"]).set_index(["name", "item"])

flags.style

In [39]:
flags.query("flag != 'Line'")

                                                 flag
name      item
HT_PHASOR quadrature                      Dashed Line
HT_SINE   leadsine                        Dashed Line
AROON     aroondown                       Dashed Line
MACD      macdsignal                      Dashed Line
          macdhist                          Histogram
MACDEXT   macdsignal                      Dashed Line
          macdhist                          Histogram
MACDFIX   macdsignal                      Dashed Line
          macdhist                          Histogram
STOCH     slowk                           Dashed Line
          slowd                           Dashed Line
BBANDS    upperband   Values represent an upper limit
          lowerband    Values represent a lower limit
MAMA      fama                            Dashed Line

In [40]:
flags.query("item not in ('real', 'integer')")

                                                   flag
name        item
HT_PHASOR   inphase                                Line
            quadrature                      Dashed Line
HT_SINE     sine                                   Line
            leadsine                        Dashed Line
MINMAX      min                                    Line
            max                                    Line
MINMAXINDEX minidx                                 Line
            maxidx                                 Line
AROON       aroondown                       Dashed Line
            aroonup                                Line
MACD        macd                                   Line
            macdsignal                      Dashed Line
            macdhist                          Histogram
MACDEXT     macd                                   Line
            macdsignal                      Dashed Line
            macdhist                          Histogram
MACDFIX     macd                                   Line
            macdsignal                      Dashed Line
            macdhist                          Histogram
STOCH       slowk                           Dashed Line
            slowd                           Dashed Line
STOCHF      fastk                                  Line
            fastd                                  Line
STOCHRSI    fastk                                  Line
            fastd                                  Line
BBANDS      upperband   Values represent an upper limit
            middleband                             Line
            lowerband    Values represent a lower limit
MAMA        mama                                   Line
            fama                            Dashed Line

In [41]:
fn = Function("SMA", 50)

def test_function(fn):
    display(fn)
    display(vars(fn))

test_function(fn)

{'name': 'SMA', 'group': 'Overlap Studies', 'display_name': 'Simple Moving Average', 'function_flags': ['Output scale same as input'], 'input_names': OrderedDict([('price', 'close')]), 'parameters': OrderedDict([('timeperiod', 50)]), 'output_flags': OrderedDict([('real', ['Line'])]), 'output_names': ['real']}

{'_Function__name': b'SMA',
 '_Function__namestr': 'SMA',
 '_Function__localdata': <_thread._local at 0x122151040>,
 'func_object': <function talib._ta_lib.SMA(real, timeperiod=-2147483648)>}

In [42]:
fn.info

{'name': 'SMA',
 'group': 'Overlap Studies',
 'display_name': 'Simple Moving Average',
 'function_flags': ['Output scale same as input'],
 'input_names': OrderedDict([('price', 'close')]),
 'parameters': OrderedDict([('timeperiod', 50)]),
 'output_flags': OrderedDict([('real', ['Line'])]),
 'output_names': ['real']}

In [43]:
fn(prices)

date
1980-12-12           NaN
1980-12-15           NaN
1980-12-16           NaN
1980-12-17           NaN
1980-12-18           NaN
                 ...
2024-05-29    176.423375
2024-05-30    176.732345
2024-05-31    177.008785
2024-06-03    177.466627
2024-06-04    177.916294
Length: 10960, dtype: float64

In [ ]:
help(abstract.Function("SMA"))

In [45]:
res = abstract.Function("MACD")(prices)
print(type(res).__name__)
res

DataFrame

                macd  macdsignal  macdhist
date
1980-12-12       NaN         NaN       NaN
1980-12-15       NaN         NaN       NaN
1980-12-16       NaN         NaN       NaN
1980-12-17       NaN         NaN       NaN
1980-12-18       NaN         NaN       NaN
...              ...         ...       ...
2024-05-29  4.371958    4.428581 -0.056623
2024-05-30  4.290437    4.400952 -0.110515
2024-05-31  4.254256    4.371613 -0.117357
2024-06-03  4.319421    4.361174 -0.041753
2024-06-04  4.361138    4.361167 -0.000029

[10960 rows x 3 columns]

In [46]:
fn

{'name': 'SMA', 'group': 'Overlap Studies', 'display_name': 'Simple Moving Average', 'function_flags': ['Output scale same as input'], 'input_names': OrderedDict([('price', 'close')]), 'parameters': OrderedDict([('timeperiod', 50)]), 'output_flags': OrderedDict([('real', ['Line'])]), 'output_names': ['real']}

In [47]:
fn.info

{'name': 'SMA',
 'group': 'Overlap Studies',
 'display_name': 'Simple Moving Average',
 'function_flags': ['Output scale same as input'],
 'input_names': OrderedDict([('price', 'close')]),
 'parameters': OrderedDict([('timeperiod', 50)]),
 'output_flags': OrderedDict([('real', ['Line'])]),
 'output_names': ['real']}

In [48]:
vars(fn)

{'_Function__name': b'SMA',
 '_Function__namestr': 'SMA',
 '_Function__localdata': <_thread._local at 0x122151040>,
 'func_object': <function talib._ta_lib.SMA(real, timeperiod=-2147483648)>}

In [49]:
vars(fn.func_object)

{'__wrapped__': <cyfunction SMA at 0x115b5ee80>}

In [50]:
str(fn)

'SMA([input_arrays], [timeperiod=50])\n\nSimple Moving Average (Overlap Studies)\n\nInputs:\n    price: (any ndarray)\nParameters:\n    timeperiod: 50\nOutputs:\n    real'

In [51]:
repr(fn)

"{'name': 'SMA', 'group': 'Overlap Studies', 'display_name': 'Simple Moving Average', 'function_flags': ['Output scale same as input'], 'input_names': OrderedDict([('price', 'close')]), 'parameters': OrderedDict([('timeperiod', 50)]), 'output_flags': OrderedDict([('real', ['Line'])]), 'output_names': ['real']}"

In [52]:
dir(fn)

['_Function__call_function',
 '_Function__check_opt_input_value',
 '_Function__get_opt_input_value',
 '_Function__input_price_series_names',
 '_Function__local',
 '_Function__localdata',
 '_Function__name',
 '_Function__namestr',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__unicode__',
 '__weakref__',
 'func_object',
 'function_flags',
 'get_input_arrays',
 'get_input_names',
 'get_parameters',
 'info',
 'input_arrays',
 'input_names',
 'lookback',
 'output_flags',
 'output_names',
 'outputs',
 'parameters',
 'run',
 'set_function_args',
 'set_input_arrays',
 'set_input_names',
 'set_parameters']

In [61]:
SMA20 = abstract.Function("SMA", timeperiod=20)

In [62]:
SMA20(prices)

date
1980-12-12           NaN
1980-12-15           NaN
1980-12-16           NaN
1980-12-17           NaN
1980-12-18           NaN
                 ...
2024-05-29    185.652359
2024-05-30    186.763325
2024-05-31    187.736044
2024-06-03    188.280963
2024-06-04    188.934269
Length: 10960, dtype: float64