# Fetching prices with yfinance

In [1]:
import yfinance as yf

from mplchart.chart import Chart
from mplchart.primitives import Candlesticks
from mplchart.utils import normalize_prices

In [2]:
# intervals: 1m, 2m, 5m, 15m, 30m, 60m, 90m, 1h, 1d, 5d, 1wk, 1mo, 3mo

def max_period(interval: str) -> str:
    if interval.endswith("m"):
        period = "5d"
    elif interval.endswith("h"):
        period = "2y"
    else:
        period = "5y"

    return period


def fetch_prices(ticker, interval=None, period=None):
    if interval is None:
        interval = "1d"

    if period is None:
        period = max_period(interval)

    prices = yf.Ticker(ticker).history(interval=interval, period=period)

    if prices.index.name == 'Date':
        prices = prices.set_index(prices.index.tz_convert(None).normalize())

    return normalize_prices(prices)


prices = fetch_prices("AAPL")
prices

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-04-19,130.038126,131.947164,129.872549,131.333542,94264200,0.0,0.0
2021-04-20,131.508864,132.005596,128.382332,129.648529,94812300,0.0,0.0
2021-04-21,128.918042,130.271895,127.885610,130.028397,68847100,0.0,0.0
2021-04-22,129.580374,130.661509,127.992771,128.508987,84566500,0.0,0.0
2021-04-23,128.723268,131.606287,128.723268,130.827103,78657500,0.0,0.0
...,...,...,...,...,...,...,...
2026-04-10,259.980011,262.190002,259.019989,260.480011,31291500,0.0,0.0
2026-04-13,259.730011,260.179993,256.660004,259.200012,36234700,0.0,0.0
2026-04-14,259.250000,261.929993,257.190002,258.829987,48370700,0.0,0.0
2026-04-15,258.160004,266.559998,257.809998,266.429993,49913500,0.0,0.0
2026-04-16,266.799988,267.160004,261.269989,263.399994,43263500,0.0,0.0

In [3]:

fetch_prices("AAPL", "1d")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-04-19,130.038126,131.947164,129.872549,131.333542,94264200,0.0,0.0
2021-04-20,131.508864,132.005596,128.382332,129.648529,94812300,0.0,0.0
2021-04-21,128.918042,130.271895,127.885610,130.028397,68847100,0.0,0.0
2021-04-22,129.580374,130.661509,127.992771,128.508987,84566500,0.0,0.0
2021-04-23,128.723268,131.606287,128.723268,130.827103,78657500,0.0,0.0
...,...,...,...,...,...,...,...
2026-04-10,259.980011,262.190002,259.019989,260.480011,31291500,0.0,0.0
2026-04-13,259.730011,260.179993,256.660004,259.200012,36234700,0.0,0.0
2026-04-14,259.250000,261.929993,257.190002,258.829987,48370700,0.0,0.0
2026-04-15,258.160004,266.559998,257.809998,266.429993,49913500,0.0,0.0
2026-04-16,266.799988,267.160004,261.269989,263.399994,43263500,0.0,0.0

In [4]:
fetch_prices("AAPL", "1h")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2024-04-17 09:30:00-04:00,169.580002,170.639999,169.310104,170.455002,10358959,0.0,0.0
2024-04-17 10:30:00-04:00,170.449997,170.475006,169.210007,169.210007,7818704,0.0,0.0
2024-04-17 11:30:00-04:00,169.220001,169.360001,168.600006,168.699997,5853359,0.0,0.0
2024-04-17 12:30:00-04:00,168.699997,168.970001,168.070007,168.820007,4690283,0.0,0.0
2024-04-17 13:30:00-04:00,168.830002,169.000000,168.509995,168.610001,4907946,0.0,0.0
...,...,...,...,...,...,...,...
2026-04-16 11:30:00-04:00,262.250000,264.389801,262.190002,264.080109,4125437,0.0,0.0
2026-04-16 12:30:00-04:00,264.089996,264.168610,263.089996,263.519989,2692302,0.0,0.0
2026-04-16 13:30:00-04:00,263.529999,264.170013,263.290009,263.579987,2435729,0.0,0.0
2026-04-16 14:30:00-04:00,263.589996,264.549988,263.480011,263.634094,3260194,0.0,0.0
2026-04-16 15:30:00-04:00,263.630005,264.250000,263.260010,263.359985,3667931,0.0,0.0

In [5]:
fetch_prices("AAPL", "1m")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2026-04-10 09:30:00-04:00,259.950012,260.549988,259.109985,259.609985,1107084,0.0,0.0
2026-04-10 09:31:00-04:00,259.570007,259.799988,259.260010,259.260010,166150,0.0,0.0
2026-04-10 09:32:00-04:00,259.279999,259.459991,259.070007,259.450012,107421,0.0,0.0
2026-04-10 09:33:00-04:00,259.489990,259.760010,259.295013,259.739990,96417,0.0,0.0
2026-04-10 09:34:00-04:00,259.730011,259.915009,259.600098,259.904999,91288,0.0,0.0
...,...,...,...,...,...,...,...
2026-04-16 15:55:00-04:00,263.670013,263.760010,263.410004,263.424988,158812,0.0,0.0
2026-04-16 15:56:00-04:00,263.424988,263.529999,263.424988,263.510010,136013,0.0,0.0
2026-04-16 15:57:00-04:00,263.515015,263.609985,263.484985,263.515015,174552,0.0,0.0
2026-04-16 15:58:00-04:00,263.519989,263.599915,263.470001,263.494995,286313,0.0,0.0
2026-04-16 15:59:00-04:00,263.500000,263.600006,263.260010,263.359985,839634,0.0,0.0

In [6]:
prices

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-04-19,130.038126,131.947164,129.872549,131.333542,94264200,0.0,0.0
2021-04-20,131.508864,132.005596,128.382332,129.648529,94812300,0.0,0.0
2021-04-21,128.918042,130.271895,127.885610,130.028397,68847100,0.0,0.0
2021-04-22,129.580374,130.661509,127.992771,128.508987,84566500,0.0,0.0
2021-04-23,128.723268,131.606287,128.723268,130.827103,78657500,0.0,0.0
...,...,...,...,...,...,...,...
2026-04-10,259.980011,262.190002,259.019989,260.480011,31291500,0.0,0.0
2026-04-13,259.730011,260.179993,256.660004,259.200012,36234700,0.0,0.0
2026-04-14,259.250000,261.929993,257.190002,258.829987,48370700,0.0,0.0
2026-04-15,258.160004,266.559998,257.809998,266.429993,49913500,0.0,0.0
2026-04-16,266.799988,267.160004,261.269989,263.399994,43263500,0.0,0.0